# objstoreConfig: |
#   type: s3
#   config:
#     bucket: "test"
#     endpoint: "minio.minio.svc.cluster.local:80"
#     access_key: "minio"
#     secret_key: "minio123"
#     insecure: true
#     prefix: "metrics"

existingObjstoreSecret: thanos-objstore-config

compactor:
  enabled: true

storegateway:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
receive:
  enabled: true